name: Taller Automation Playwright E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  playwright-e2e-job:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      STANDARD_USER_EMAIL: ${{ secrets.STANDARD_USER_EMAIL }}
      STANDARD_USER_PASSWORD: ${{ secrets.STANDARD_USER_PASSWORD }}
      UI_BASE_URL: ${{ secrets.UI_BASE_URL }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      REQRES_API_KEY: ${{ secrets.REQRES_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test
        
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: reports/playwright-report/
          retention-days: 30

      - name: Upload Monocart Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: monocart-report
          path: reports/monocart-report/
          retention-days: 30

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-report
          path: reports/lighthouse-report/
          retention-days: 30          

      - name: Debug Playwright configuration
        run: cat playwright.config.ts

      - name: Final check
        run: |
          if [[ $(npm run test | grep -c "failed") -gt 0 ]]; then
            echo "Playwright tests failed"
            exit 1
          else
            echo "All Playwright tests passed"
          fi
        continue-on-error: false
    outputs:
      test_status: ${{ job.status }}  